using System;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.Compilation;
using UnityEditor.UnityLinker;

namespace Pragma.CommandExecutor
{
    /// <summary>
    /// Generates a link.xml for every player build that keeps all command and processor types whole, including the
    /// ones declared in user assemblies:
    /// <list type="bullet">
    /// <item>processors are created by reflection from the registered types, so their constructors look unused to the
    /// linker, and Medium or High stripping removes them together with the rest of the never instantiated type;</item>
    /// <item>command types may be referenced only from serialized data that the build does not scan
    /// (asset bundles, Addressables).</item>
    /// </list>
    /// </summary>
    internal sealed class CommandExecutorLinkerProcessor : IUnityLinkerProcessor
    {
        private const string OUTPUT_PATH = "Library/Pragma.CommandExecutor/link.xml";

        public int callbackOrder => 0;

        public string GenerateAdditionalLinkXmlFile(BuildReport report, UnityLinkerBuildPipelineData data)
        {
            // Editor-only assemblies (editor code, tests) never reach the player.
            var editorAssemblies = CompilationPipeline.GetAssemblies(AssembliesType.Editor)
                .Select(assembly => assembly.name)
                .Except(CompilationPipeline.GetAssemblies(AssembliesType.Player).Select(assembly => assembly.name))
                .ToHashSet();

            var assemblies = TypeCache.GetTypesDerivedFrom<ICommandProcessor>()
                .Concat(TypeCache.GetTypesDerivedFrom<ICommand>())
                .Where(type => !type.IsInterface && !editorAssemblies.Contains(type.Assembly.GetName().Name))
                .GroupBy(type => type.Assembly.GetName().Name)
                .OrderBy(assembly => assembly.Key, StringComparer.Ordinal);

            var xml = new StringBuilder();
            xml.AppendLine("<!-- Generated by Pragma.CommandExecutor.CommandExecutorLinkerProcessor for the current build. -->");
            xml.AppendLine("<linker>");

            foreach (var assembly in assemblies)
            {
                // A precompiled plugin excluded from this platform is simply skipped.
                xml.AppendLine($"  <assembly fullname=\"{SecurityElement.Escape(assembly.Key)}\" ignoreIfMissing=\"1\">");

                foreach (var typeName in assembly.Select(GetLinkerName).Distinct().OrderBy(name => name, StringComparer.Ordinal))
                {
                    xml.AppendLine($"    <type fullname=\"{SecurityElement.Escape(typeName)}\" preserve=\"all\"/>");
                }

                xml.AppendLine("  </assembly>");
            }

            xml.AppendLine("</linker>");

            var path = Path.GetFullPath(OUTPUT_PATH);
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, xml.ToString());
            return path;
        }

        // link.xml separates nested types with '/'; generic definitions keep their `N arity suffix, as in metadata.
        private static string GetLinkerName(Type type)
        {
            return type.FullName.Replace('+', '/');
        }
    }
}
